### ISSUE TITLE
Essential Features To-Do List

### ISSUE THREAD

**Issue by seanmishra** [priyasonali/recipe-manager#37]
- [x] Register
- [x] Email Activation
- [x] Password Confirmation
- [x] Login
- [x] Landing
- [x] Register Button Logged In Check
- [x] Register Success Redirection
- [x] Login Success Redirection
- [x] Forgot Password
- [x] Primary Navigation
- [ ] Reset Password
- [ ] Logout
- [ ] Persistent Login

**Comment by seanmishra** [comment]
Primary Navigation completed in PR #38

**Comment by seanmishra** [comment]
Forgot Password completed in PR #39
